bcn:
  heads: 2
predict:
  binary: 2
  hidden_dim: 256
  in_dim: 256
  name: MLP
  out_dim: 256
  simple: false
protein:
  channel: 192
  dropout: 0.5
  max_antibody_len: 66
  max_antigen_len: 218
  padding: true
  use_bn: true
result:
  output_dir: ./result
  save_model: true
set:
  ab_model: ablang
  alpha: 0.4
  dataset: HIV
  device: 0
  model_name: DeepInterAware
  phy: false
  pretrain: false
  project: true
  resume_path: null
  unseen_task: unseen
solver:
  batch_size: 512
  lr: 0.001
  num_workers: 0
  seed: 0
  train_epoch: 30
  weight_decay: 0
  end_epoch: 20
